### ISSUE TITLE
你好，包无法安装

### ISSUE THREAD

**Issue by zengonly** [mwz747512353/laravelAdmin-echarts#1]
你好，包无法安装
![image](https://user-images.githubusercontent.com/21103564/53236800-1d0d0200-36d0-11e9-9f6f-d4f5ba4de007.png)

**Comment by mwz747512353** [comment]
是否安装了laraveladmin？

**Comment by mwz747512353** [comment]
是否安装了laraveladmin？

**Comment by mwz747512353** [comment]
您好，包重新发布 composer require mwz747512353/laravel-admin-echarts
